### ISSUE TITLE
Issue while testing Patient Standalone App - Full Access

### ISSUE THREAD

**Issue by VirajKheni** [Azure-Samples/azure-health-data-and-ai-samples#105]
![image](https://github.com/Azure-Samples/azure-health-data-services-samples/assets/69363980/d6ae8026-4c00-4015-9a4c-e512b80be8a7)

I'm following this doc: https://github.com/Azure-Samples/azure-health-data-services-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/deployment.md
I've followed each steps. But while testing the Standalone App for Patient - I'm getting an error. I've uploaded a screenshot for the same. 

I've cross-checked the settings for the roles and permissions. Adding another snapshot of the roles & permissions I've given to  my app.

![image](https://github.com/Azure-Samples/azure-health-data-services-samples/assets/69363980/d69e38d6-9aef-4457-940e-f4896c439937)

Find another snapshot of application administrator rights that has been given to my auth function application. 

![image](https://github.com/Azure-Samples/azure-health-data-services-samples/assets/69363980/36fae19e-b28c-49c0-9d95-daf371fc7fc4)

**If anyone is familiar with this issue or know how to resolve it, I would greatly appreciate your assistance.**

**Comment by EXPEkesheth** [comment]
Thanks for reporting the issue @VirajKheni . We will look into it and report back the findings.

**Comment by VirajKheni** [comment]
Thanks for your response @EXPEkesheth, I require your assistance to solve this issue. Your timely support in addressing this matter is highly valued.

**Comment by sordahl-ga** [comment]
@VirajKheni You should be authenticating using the dedicated standalone app that has smart scopes delegated from your smart-aad application that is detailed here:

https://github.com/Azure-Samples/azure-health-data-services-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/ad-apps/inferno-test-app-registration.md

Your registration should look something like this:
<img width="846" alt="support" src="https://github.com/Azure-Samples/azure-health-data-services-samples/assets/29715304/ea09974a-68ac-4afd-b66f-175694c756f8">

Use this applications client id and secret with the onc inferno test suite....for stand alone patient confidential client test.

**Comment by VirajKheni** [comment]
@sordahl-ga thanks for your input. I've already given all permission which is mentioned in doc. but still, the issue remains the same.
![image](https://github.com/Azure-Samples/azure-health-data-services-samples/assets/69363980/1e4785a4-feed-411a-9991-191728f65af3)

**Comment by EXPEkesheth** [comment]
@VirajKheni - we will try to repro the issue and report back the finding.

**Comment by evachen96** [comment]
@VirajKheni  - We weren't able to reproduce this issue, could you let us know the parameters that were sent to the /appConsentInfo endpoint? Also, are you setting up the correct authorization ie: sending the Authorization: Bearer tokenheader (with token being the access_token returned from the SMART on FHIR /token endpoint)?

**Comment by VirajKheni** [comment]
Thank you for your input @evachen96. this issue is resolved by redeploying the auth context frontend app and auth function backend app.

**Comment by EXPEkesheth** [comment]
Closing as issue is fixed
