### ISSUE TITLE
Issue openid and offline_access while testing Patient Standlone Full access ONC test suite

### ISSUE THREAD

**Issue by VirajKheni** [Azure-Samples/azure-health-data-and-ai-samples#108]
![image](https://github.com/Azure-Samples/azure-health-data-services-samples/assets/69363980/99c91a1b-4695-4e67-be56-25000f090ed5)

here you find the API permissions that I gave to the patient client app on AAD.

![image](https://github.com/Azure-Samples/azure-health-data-services-samples/assets/69363980/0278d461-4981-4cd6-a9b7-a34da9ae493e)

I'm giving as default as openid and offline_access as a scope.

![image](https://github.com/Azure-Samples/azure-health-data-services-samples/assets/69363980/3834dd6c-4501-4d86-afdf-f106e47c2ae8)

and I'm selecting the below scopes while launching the app

![image](https://github.com/Azure-Samples/azure-health-data-services-samples/assets/69363980/053913f5-71c3-40e1-92d9-de91821b2c2d)

after I continue it's asked to accept the permissions

![image](https://github.com/Azure-Samples/azure-health-data-services-samples/assets/69363980/1c9c0ab3-0990-442d-998f-ca042a7d9a87)

After accepting the permission and login it will redirect to our test suite.

**Comment by EXPEkesheth** [comment]
@VirajKheni - thanks for reporting the issue , we will investigate and report back

**Comment by evachen96** [comment]
@VirajKheni  - We are not able to repro this issue, can you check the configurations from the deployment document and try the steps again to see if the issue still persists?

**Comment by EXPEkesheth** [comment]
@VirajKheni closing this issue. Please reach out if you need additional guidance or are able to repro the issue.
