### ISSUE TITLE
POST call to $FhirUrl to load profiles data returns Authentication failed.

### ISSUE THREAD

**Issue by nimesh13** [Azure-Samples/azure-health-data-and-ai-samples#110]
Hi,

I am following this doc to deploy the sample app: https://github.com/Azure-Samples/azure-health-data-services-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/deployment.md

I am on the last step of the doc where we run this:
`pwsh ./scripts/Load-ProfilesData.ps1`

The last 2 commands in the Load-ProfilesData script return this:
<img width="1512" alt="image" src="https://github.com/Azure-Samples/azure-health-data-services-samples/assets/26820845/29167e9f-2ad3-44f8-8df2-dbcd90383d69">

Have already tried logging in multiple times but this error always shows up.
My [FHIR Resource App](https://github.com/Azure-Samples/azure-health-data-services-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/ad-apps/fhir-resource-app-registration.md) is in a different resource group and my Fhir Service, which corresponds to the $FhirUrl, is in the resource group that gets created when we deploy the app. Could that be a problem?

**Comment by EXPEkesheth** [comment]
@nimesh13 - we would look into this and report back

**Comment by evachen96** [comment]
@nimesh13  - Are our FHIR Resource App and FHIR service in different domains or resource groups? We were able to repro this issue with different domains, if that is the case for you as well, you can create the FHIR Resource App and FHIR service in the same domain, and that should be able to solve this issue. Let us know!

**Comment by nimesh13** [comment]
Yes I think the problem was different resource groups. Closing the issue.
