### ISSUE TITLE
Issue while testing Patient Standalone App - Full Access

### ISSUE THREAD

**Issue by HitakshiDobariya99** [Azure-Samples/azure-health-data-and-ai-samples#111]
I'm following this document for the implementation of SMART on FHIR: https://github.com/Azure-Samples/azure-health-data-services-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/deployment.md  

I have diligently completed each step of the deployment process. However, while testing the Standalone App for Patients, I encountered an error. 

![image](https://github.com/Azure-Samples/azure-health-data-services-samples/assets/101874176/8108fa06-b6c4-4707-a2e8-cbf74a2283f2)

I have verified the roles and permissions settings thoroughly and assigned permissions for my application. Also, I gave the Administrator rights to Auth function app for modifying signed user permissions. 

Kindly seek your expertise to resolve this issue. 
Your assistance will be highly appreciated.
Thank you.

**Comment by VirajKheni** [comment]
I'm facing the same issue. If is there anyone who knows then will be very appreciative.

https://github.com/Azure-Samples/azure-health-data-services-samples/issues/105

**Comment by nimesh13** [comment]
Hey can you guys let me know how you are testing this? I probably missed this in the docs but I can only find the extensive postman APIs and the inferno tool only.

**Comment by HitakshiDobariya99** [comment]
Hello,
I'm testing **Standalone Patient App - Full Access** from the Inferno test suite. In this testing, I'm giving APIM smart baseUrl, client app id, and secret which has the patient's scope. 
https://inferno.healthit.gov/suites/g10_certification/dfCEkR56ZIC#1

**Comment by EXPEkesheth** [comment]
Thanks for reporting the issue, we will investigate and report back

**Comment by nimesh13** [comment]
@HitakshiDobariya99 oh the inferno tool, okay. I tried with the APIM gateway URL, standalone client app id and secret but it returns a 404 resource not found. I added the standalone app to the fhir service IAM roles too. 
<img width="1134" alt="image" src="https://github.com/Azure-Samples/azure-health-data-services-samples/assets/26820845/f54fbef4-2f6e-4ce9-8972-8c5c37b9a41f">

Any idea?

**Comment by VirajKheni** [comment]
Hello @nimesh13

I think it's a base URL mistake. You need to give **APIM gateway URL/smart** as a base Url.

**Comment by nimesh13** [comment]
@VirajKheni oh yes this worked!! Thanks! But is this documented anywhere?

**Comment by nimesh13** [comment]
So I am also stuck on a similar issue: 

<img width="1482" alt="image" src="https://github.com/Azure-Samples/azure-health-data-services-samples/assets/26820845/7549dde5-b81e-4da1-b795-c8dd3615d6d2">

<img width="1163" alt="image" src="https://github.com/Azure-Samples/azure-health-data-services-samples/assets/26820845/a808bdfb-87d2-4fc1-a783-68785381b6fc">

**Comment by EXPEkesheth** [comment]
@erikhoward - can you please check on the documentation issue mentioned by Viral above? 

@nimesh13 - is this a different issue mentioned from original one ? If yes, can you please share more details and create new issue?

**Comment by nimesh13** [comment]
@EXPEkesheth - yes I have moved the discussion to a new issue.

**Comment by EXPEkesheth** [comment]
Documentation updated and hence closing the issue

**Comment by HitakshiDobariya99** [comment]
This issue is resolved now. You can close the issue.
