### ISSUE TITLE
The fhirUser claim is not returned for the user

### ISSUE THREAD

**Issue by dimangulov** [Azure-Samples/azure-health-data-and-ai-samples#121]
Client application has proper configuration, the extension property mapped to a claim

<img width="505" alt="image" src="https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/6388017/31b86a92-6c94-4985-b2f1-31d10802430a">

<img width="266" alt="image" src="https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/6388017/cf72e5c7-0325-459f-b6e5-744c1fcdf357">

The property's value is set, but I don't see the property in the final JWT token.

In order to troubleshoot the issue, I added the extn.fhirUser claim to the optional claims list.

Do you have an idea why the mapping doesn't work and I don't receive the **fhirUser** claim in the final token?

Following the docs -> https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/smartonfhir/docs/ad-apps/set-fhir-user-mapping.md

**Comment by nimesh13** [comment]
Hey how did you resolve this? I am facing the same issue.
