### ISSUE TITLE
SMART on FHIR using existing FHIR server

### ISSUE THREAD

**Issue by EXPEkesheth** [Azure-Samples/azure-health-data-and-ai-samples#132]
Provide parameters in SMART on FHIR proxy to set up with existing FHIR server account, as we would want to deploy sample on existing FHIR server.
Ask: 
1. Determine the documentation steps
2. Validate script can support the parameter

**Comment by EXPEkesheth** [comment]
Work around:
Go to samples/smartonfhir/infra/main.bicep and update below listed parameters

 

@description('Do you want to create a new Azure Health Data Services workspace or use an existing one?')

param createWorkspace bool = false

 

@description('Do you want to create a new FHIR Service or use an existing one?')

param createFhirService bool = false

 

@description('Name of Azure Health Data Services workspace to deploy or use. Leave blank for default.')

param workspaceName string = ''

 

@description('Name of the FHIR service to deloy or use. Leave blank for default.')

param fhirServiceName string = ''

**Comment by EXPEkesheth** [comment]
@erikhoward can you please take a look at this one?

**Comment by evachen96** [comment]
Resolved with PR [Personal/sgupta/existingfhirservice by v-shresgupta · Pull Request #168 · Azure-Samples/azure-health-data-and-ai-samples (github.com)](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/pull/168)
