### ISSUE TITLE
SMART Deployment Doc Suggestions [Bug Bash]

### ISSUE THREAD

**Issue by mikaelweave** [Azure-Samples/azure-health-data-and-ai-samples#133]
- "Use the terminal or your git client to clone this repo. Open a terminal to the `smartonfhir` folder."
  - *NIT: Would be nice if it has the whole path in the repo`samples/smartonfhir`.
- In `samples/smartonfhir/infra/main.bicep` should we change the default `createWorkspace` and `createFhirServer` parameters?
- Do we need instructions to tell users how to set their workspace name and fhir service name?
- Getting - *WARNING: `azd login` is deprecated and will be removed in a future release.*
  - Update instructions to use `azd auth login`.
- `fhir-resource-app-registration.md` Step 3 - would be helpful to have a more templated name here. Like `<appname>.<primaryName>`. The `my-app-1` is a bit confusing to me.
- Would be nice to have a PowerShell script or Azure CLI script to setup the Application Registration instead of modifying JSON app manifest.
- `FhirUserDirectoryExtension.ps1` uses Azure CLI Auth and we only tell users to login with azd. I think they will need to login with both in prepare environment.
- `samples/smartonfhir/docs/ad-apps/set-fhir-user-mapping.md` talks about (g)(10) is this in scope for this doc?
- NIT: Section [Configure fhirUser mapping to token](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/smartonfhir/docs/ad-apps/set-fhir-user-mapping.md#configure-fhiruser-mapping-to-token) step one has a `*` instead of a `&` to match AAD.
- [This section](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/smartonfhir/docs/ad-apps/set-fhir-user-mapping.md#modify-application-manifest) is a repeat of earlier in the doc - accept mapped claims to true.
- `samples/smartonfhir/docs/deployment.md` section 2 step 4 talks about making sure to inform azd about one value not both from the linked docs page.
- `samples/smartonfhir/docs/deployment.md` section 2 step 6 has repeat values from steps 4 and 5 being set. I think they only need to set the APIM values? 
- NIT: `samples/smartonfhir/docs/deployment.md` section 2 step 7 has a dash vs a sub-bullet like the other steps in this section.
- NIT: `samples/smartonfhir/docs/deployment.md` section 2 step 7: `azd` does ask some questions. Might be nice to highlight this so users don't switch screens before deployment starts.
- If deploying to a FHIR Server in another resource group - you get an error. Resource Group name is created automatically. Might make sense to have users enter in the resource group name as a parameter. Deployment in `main.bicep` is currently subscription scope. Change to resource group scope and have user ender maybe?

**Comment by EXPEkesheth** [comment]
@erikhoward can you please help with these?
