### ISSUE TITLE
The Resource APIM under resource group was not found

### ISSUE THREAD

**Issue by nimesh13** [Azure-Samples/azure-health-data-and-ai-samples#144]
I am trying to install Smart-on-fhir again in a new instance and when I run `azd up` command I get this error:

======
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
ResourceNotFound: The Resource 'Microsoft.ApiManagement/service/sfhirv2-apim' under resource group 'sfhirv2-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

TraceID: 1234xyz

### Full screenshot:
<img width="1512" alt="image" src="https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/26820845/79416a0a-11ec-4a47-90fe-2a71cec727a9">

### The APIM instance exists in the resource group created as part of the deployment:
<img width="1232" alt="image" src="https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/26820845/df83992a-1302-486f-b71b-2ee9824d2931">

**Comment by evachen96** [comment]
Thanks for submitting this issue, we will look into it and get back to you!

**Comment by evachen96** [comment]
Hi @nimesh13  - are you still facing this issue? Which sample app repo path are you using? This issue has been fixed in the repo at code path https://github.com/Azure-Samples/azure-health-data-and-ai-samples/tree/main/samples/smartonfhir .

**Comment by evachen96** [comment]
@nimesh13  Closing the issue for now, please feel free to reopen if you're still facing issues!
