### ISSUE TITLE
Inferno EHR Practitioner test - How will the EHR App redirect to inferno?

### ISSUE THREAD

**Issue by nimesh13** [Azure-Samples/azure-health-data-and-ai-samples#145]
I am running the Inferno test 3 - EHR Practitioner Test and it reaches the User Action Required step where it is waiting for EHR to redirect to inferno. However, there is no trigger point for this EHR application. How will it redirect?

### This is the screenshot:
<img width="602" alt="image" src="https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/26820845/d9169aeb-fc91-4c21-9f9e-99fa301e6b59">

What needs to be done here so that EHR sends the request to inferno?

### As per the deployment document, I added this redirect URI to the EHR app:
<img width="965" alt="image" src="https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/26820845/f819e861-ce0a-48a7-a269-781559294e79">

**Comment by evachen96** [comment]
Thanks for submitting, we'll look into this and get back to you!

**Comment by evachen96** [comment]
Hi @nimesh13  - our team has investigated this issue. When running Inferno test 3, in the User Action Required step where it is waiting for the EHR to redirect to Inferno, there is a link in the Inferno test window under the EHR Practitioner App window that contains the steps to run it successfully. Here is the link: https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/Completing-EHR-Practitioner-App-test-in-Internet-Explorer/

Please try this out and let us know if you are still facing issues. Thanks!

**Comment by nimesh13** [comment]
Hi @evachen96 - I have just followed the deployment steps from the repository. We don't have an EHR app or interface yet that will redirect to the inferno URL, as mentioned in the link. How do I use the repository resources to open the EHR UI? It's not clear to me. Can you please help highlighting the lower level steps?

**Comment by evachen96** [comment]
@nimesh13 Once you have the EHR app configured, please follow the steps in the link above and let us know if you have any other issues at that point, thanks!
