### ISSUE TITLE
Smart on FHIR Provision Issue

### ISSUE THREAD

**Issue by VirajKheni** [Azure-Samples/azure-health-data-and-ai-samples#149]
I'm Provisioning Smart on FHIR in east us regions. but facing issues.

Static Web App Issue:
![image](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/69363980/59e3b3b1-e803-413e-a234-e4453a7fa482)

Azure Health data service Issue:
![image](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/69363980/3fbc8532-1e2e-40e6-be46-ea5d34dde055)

apimRedisLinkDeploy Issue:
![image](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/69363980/1230c2d4-4d4b-4815-9cf8-8ae77945f7e8)

**Comment by evachen96** [comment]
Hi @VirajKheni  - Thanks for submitting this issue! This sample uses Microsoft Graph extension, and that extension can only be used in certain regions. Please change your region to EastUS2, WestUS2, or CentralUS. Let us know if that resolves the issue.

Thanks for bringing this to our attention, we will update our documentation and allowed regions list as well.

**Comment by evachen96** [comment]
@VirajKheni Closing this issue as we have not heard back. Please reopen and let us know if you are still facing issues!
