### ISSUE TITLE
Integration Issue: Conflicting Functionality between DICOMCast and Smart on FHIR

### ISSUE THREAD

**Issue by HitakshiDobariya99** [Azure-Samples/azure-health-data-and-ai-samples#150]
I've successfully deployed [DICOM Cast](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-dicom-cast.md#deploy-via-azure-with-oss) and [SMART on FHIR](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/deployment.md) in my Azure environment. However, I am encountering an integration issue related to the audience configuration.

During the deployment of DICOM Cast, The audience of the FHIR service to be the same as the FHIR service's endpoint, aligning with the default behavior.

Conversely, during the deployment of SMART on FHIR, the audience is set to the Application ID URI of the fhir-resource-app. This divergence in audience configuration is causing a conflict in integration.

To make DICOM Cast work, I need to align the FHIR service audience with the FHIR endpoint. However, doing so disrupts the functionality of SMART on FHIR.

Aligning the FHIR audience with the application ID URI of fhir-resource-app allows SMART on FHIR to work but breaks DICOM Cast.

I need guidance on how to reconcile these conflicting audience configurations to ensure the seamless integration of DICOM Cast and SMART on FHIR.

**Comment by evachen96** [comment]
@HitakshiDobariya99 thanks for reporting the issue, we'll look into this and get back to you!

**Comment by HitakshiDobariya99** [comment]
@evachen96 thanks for the reply. Could you please look into this matter ASAP? Your support in this matter will be appreciated.

**Comment by evachen96** [comment]
@HitakshiDobariya99 We are looking into it and will let you know when we have an update!

**Comment by evachen96** [comment]
@HitakshiDobariya99 Thanks for your patience, we do have a planned fix in the FHIR server that should also help address this issue, it is considered for delivery in the next few months. I can update you when it's out!

**Comment by HitakshiDobariya99** [comment]
@evachen96 Thanks for the reply.

**Comment by HitakshiDobariya99** [comment]
Hello @evachen96 

Thank you for providing information about the planned fix in the FHIR server. 
I appreciate your efforts in addressing the issue. As of now, I would like to inquire about the current status of my integration problem. Has the planned fix been implemented, and if so, is there any update on the resolution of my issue? Your assistance in checking the status would be highly valuable. 

Thank you again for your support!

**Comment by evachen96** [comment]
Hi @HitakshiDobariya99 - update is the same as last time. Thanks for your patience!

**Comment by evachen96** [comment]
HI @HitakshiDobariya99, thanks for your patience. Unfortunately at this time we cannot provide any support, as DICOMCast has been retired.
