### ISSUE TITLE
Seeking Guidance on Modifying Scopes and Enabling Write Access for Smart on FHIR Patient and Provider App

### ISSUE THREAD

**Issue by VirajKheni** [Azure-Samples/azure-health-data-and-ai-samples#156]
![Smart on FHIR Scope Issue](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/69363980/07452ce7-2944-47bb-8f19-df55be518296)

I am currently working on the Scheduling Appointments feature, following the steps outlined in the [Deployment](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/smartonfhir/docs/deployment.md) document. Thus far, the setup has been successful, and the application is running smoothly.

However, I have encountered a requirement to modify the scope manifest/expose APIs specifically for the "Appointment","Slot", "Schedule" and "PractitionerRole" resources to scheduling appointments. I would appreciate your guidance on how I can make these modifications.

Furthermore, the existing scopes appear to be configured only for reading access for patient and provider. If I need to implement write or update operations for these resources, I'd like to understand the correct approach to achieve this. I've attempted to follow the instructions outlined in the [App Launch: Scopes](https://build.fhir.org/ig/HL7/smart-app-launch/scopes-and-launch-context.html#scopes-for-requesting-fhir-resources) documentation, but unfortunately, the changes are not taking effect as expected.

Could you kindly provide assistance or direct me to the relevant documentation or resources that can guide me through these modifications? Your expertise and support are highly appreciated.

Thank you in advance.

**Comment by evachen96** [comment]
@VirajKheni  Thanks for submitting your issue, we will look into it and get back to you!

**Comment by VirajKheni** [comment]
Okay, Thanks for the reply @evachen96.

**Comment by evachen96** [comment]
Hi @VirajKheni - 
For adding scopes to the FHIR resource app:

1. You can add a new scope in the "oauth2Permissions" array in the manifest.json file of the FHIR resource app. Example below: 
<img width="858" alt="image" src="https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/33711652/2d1bdfae-9c37-4663-9688-cfe7defeb4d8">

2. Or, you can also add it from the "Expose an API" blade of the FHIR resource app by clicking on "Add a scope" button. Example below:
<img width="816" alt="image" src="https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/33711652/623e027a-35a1-4217-a46b-aa5f49c35f59">

3. Once added, these scopes would be available for adding as permission from the "API permissions" blade on required AD application

For the second query on how to implement write/update operations for the resources, we're still looking into that and will respond when we have an answer! Thanks for your patience.

**Comment by VirajKheni** [comment]
Hello @evachen96 

I appreciate your prompt reply and your guidance. I have followed your instructions and added a new scope in the "oauth2Permissions" for Practitioner, PractitionerRole, and Slot resources. I have also granted the necessary permissions to the relevant AD apps. However, I am still unable to read these resources. Could you please help me troubleshoot this issue?

**Comment by evachen96** [comment]
@VirajKheni Could you let me know which scopes you added? Was it read-only?

**Comment by VirajKheni** [comment]
Hi @evachen96, I have added the following scopes, and it's read-only but I am unable to read marked resources. 

![scope issue](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/69363980/7c4912d9-86f2-4c35-8111-d2c5286bb295)

**Comment by evachen96** [comment]
@VirajKheni , can you share what error you are getting for these? Is it an unauthorized error?

**Comment by VirajKheni** [comment]
Hello @evachen96, 

I encountered an error when I tried to fetch Slot.

Error: Resource type 'Slot' with id 'ee79584c-847a-4457-9eb8-d864dd556c2c' couldn't be found.

I have attached the access token scope for your reference:
![image](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/69363980/f9a91636-a5aa-4c6f-87b6-9ee390ca1ce7)

However, the data exists in my FHIR service. Here is a screenshot of the query result for this specific slot in Postman.
![image](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/69363980/505f0fa6-ca6c-45fb-9566-ac94ec0ac8ee)

**Comment by evachen96** [comment]
Hi @VirajKheni  - thanks for your patience as we investigated on this one. 

In regards to the earlier question on Write scopes, we do not support write scopes at this time. Please see the notice here: https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/smart-on-fhir#step-1-set-up-fhir-smart-user-role

For accessing Slot, Slots are not part of a [patient compartment](https://hl7.org/fhir/R4/compartmentdefinition-patient.html) because they are not patient-specific, so by default, you cannot access Slot from the patient compartment. If you are hosting your own data, you can choose to establish your own policy. One possible policy would be to make Slots available to certain or all clients. Or, you could have a policy for Slot access based on the Slot -> Schedule -> Actor. For example, an app could see slots associated with the schedule of their own user, or for that user's primary care provider or org. 

Hopefully that helps!
