### ISSUE TITLE
Running setup script Create-FhirUserDirectoryExtension.ps1 fails

### ISSUE THREAD

**Issue by muthink** [Azure-Samples/azure-health-data-and-ai-samples#173]
Following deployment instructions for https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/ad-apps/fhir-resource-app-registration.md
fails with script, using powershell 7:
patientandpopulationservices-smartonfhir-oncg10/scripts/Create-FhirUserDirectoryExtension.ps1:

ParserError: C:\github\azure-health-data-and-ai-samples\samples\patientandpopulationservices-smartonfhir-oncg10\scripts\Create-FhirUserDirectoryExtension.ps1:23
Line |
  23 |          if ([string]::IsNullOrWhiteSpace($name) +or $name.Contains('# …
     |                                                   ~
     | You must provide a value expression following the '+' operator.

**Comment by evachen96** [comment]
Thanks for your feedback @muthink , the team is looking into your comment on the PR!

**Comment by evachen96** [comment]
@muthink The team has looked more into your comment on the PR. The error message indicates that the resource 'a33cc436-eb3a-42ac-bfb3-dde37ee53e54' does not exist. This issue occurs when the environment variable FhirResourceAppId is not properly set. You can check if the application with the ID 'a33cc436-eb3a-42ac-bfb3-dde37ee53e54' exists in the tenant where the sample is being deployed. Step 5 in the [deployment doc](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/ad-apps/fhir-resource-app-registration.md
) details how to set this environment variable with the correct FHIR resource app id, using the following command:
azd env set FhirResourceAppId <FHIR Resource App Id>

Let us know if this helps!

**Comment by evachen96** [comment]
Hi @muthink  we'll close this issue since we haven't heard back, but feel free to reopen or submit a new issue if you have any more issues!
