### ISSUE TITLE
Issue with using SMART on FHIR feature from Postman

### ISSUE THREAD

**Issue by swapnilkotimw** [Azure-Samples/azure-health-data-and-ai-samples#190]
Hello experts,

We have deployed services required for implementing SMART on FHIR using the sample here.
The services were deployed successfully, no error/warning messages, we also created 2 sample/test users on our Entra ID to link them to patient IDs on our FHIR store. But when we try to use the deployed services, as described in the link, with a call from Postman, we are unable to generate a token. Here is the screenshot of the error we are getting,

<img width="796" alt="Screenshot 2024-04-11 at 8 53 43 AM" src="https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/164126268/f15e326d-47fb-4d77-a9af-bed1b8d4834a">

![Screenshot 2024-04-11 at 8 54 20 AM](https://github.com/Azure-Samples/azure-health-data-and-ai-samples/assets/164126268/febed8c4-ef87-41f5-aea1-2687d5fa8a4b)

Thank you for your help and support.

**Comment by evachen96** [comment]
Hi @swapnilkotimw ! Thanks for submitting your issue. The team has taken a look, and this error occurs when some files are not properly copied over or some configuration variables are not properly set when deploying the sample. You can rerun the **azd up** command (no need to perform any other steps) to redeploy the sample from the terminal where it was originally deployed. This should solve the issue. Let us know if that doesn't work!

**Comment by evachen96** [comment]
Closing this for now as we have not heard back. Feel free to reopen or submit a new issue if anything else comes up!
