### ISSUE TITLE
Support for setting up this sample with another type of FHIR Server?

### ISSUE THREAD

**Issue by mel-pars** [Azure-Samples/azure-health-data-and-ai-samples#193]
Hello, 

I was able to set up this sample as-documented successfully, thank you! Is there any documentation or support for setting up this sample with a different type of FHIR Server? I'd like to set up this Azure SMART on FHIR sample, for example, only with a different proprietary FHIR Server deployed as an Azure Web App. I'd appreciate any help with this!

Thank you

**Comment by evachen96** [comment]
Hi @mel-pars, thanks for your question! This sample only supports Azure API for FHIR and the FHIR service in Azure Health Data Services.
