### ISSUE TITLE
Cannot able to insert data into Azure Fhir Data Service From POSTAMAN

### ISSUE THREAD

**Issue by Kedar782** [Azure-Samples/azure-health-data-and-ai-samples#215]
Hello Team,

I'm trying to insert data into my FHIR data service using client credntials workflow in POSTMAN. I can able to generate the access token but when I use the access token I get the 401 error Unauthorized error.

I'm trying to follow below document to insert the data into my fhir data service.

https://github.com/Azure-Samples/azure-health-data-and-ai-samples/tree/main/samples/sample-postman-queries

I have assigned FHIR data contributor role for the user and Service principal on the data service.
I also created a client secret and client id. I can insert the data using the SMART on FHIR service using the OAuth 2.0 flow.

But I want to insert the data into fhir service using the client credentials flow without SMART on the FHIR data service.

I will really appreciate your help on this.

Please let me know if you need any help on this.

![image](https://github.com/user-attachments/assets/77302b33-676d-4857-92f5-d5a9a8ccd3f6)
![image](https://github.com/user-attachments/assets/90bf7f38-19f9-4f55-974d-edfdfb76c47a)

**Comment by evachen96** [comment]
For the FHIR service **without** SMART on FHIR, are you getting 401 error with Postman?
And for the FHIR service **with** SMART on FHIR, are you getting 401 error with Postman?

**Comment by Kedar782** [comment]
Yes, both.

**Comment by evachen96** [comment]
Hi @Kedar782 , apologies, I was out recently and catching up on everything now. 

We have reviewed the Postman environment file "fhir-service.postman_environment". From the provided additional information, it seems that you were able to insert data using the SMART on FHIR service with the OAuth 2.0 flow.
 
However, it looks like you are encountering issues with the client credential flow. Please ensure that you are using the correct FHIR audience in the Postman environment variable as shown below:
 
              {
			"key": "resource",
			"value": "<FHIR Audience>",
			"enabled": true
		}
 
Replace <FHIR Audience> with actual FHIR Audience URL that can be obtained from the Azure portal as follows:
![image](https://github.com/user-attachments/assets/d6442f84-6da5-4d1c-add9-150110319fab)

Let me know if this helps!

**Comment by Kedar782** [comment]
Hello @evachen96 ,

I did change the resource URL but still no luck. I'm getting 401 unauthorized error again.
Please see the attached screenshot.

![image](https://github.com/user-attachments/assets/39d72720-534c-41f0-8c67-a5c528413839)
![image](https://github.com/user-attachments/assets/37173b6d-64ca-481e-9056-6f79faf80ef3)
![image](https://github.com/user-attachments/assets/e009334b-b913-4f1f-885f-fb3f396be2d8)

Please let me know what I'm doing wrong here.
