### ISSUE TITLE
Is there sample FHIR data that I can use to play around with Azure Health Data Services?

### ISSUE THREAD

**Issue by jagandecapri** [Azure-Samples/azure-health-data-and-ai-samples#217]
Hi Azure team, 

Thank you for this helpful repository. 💯 

I am looking for sample FHIR data, e.g.: tens or hundreds of patient data,  that I could import into Azure Health Data which I can then use to experiment with the various features of Azure Health Data Services.

Is there such FHIR data available?

**Comment by evachen96** [comment]
Hi @jagandecapri , thanks for your question! 

If you're using Postman to interact with your FHIR server, we have a Postman sample (https://github.com/Azure-Samples/azure-health-data-and-ai-samples/tree/main/samples/sample-postman-queries) that can post a bundle of sample data to your FHIR service, specifically at the "Step 2 - Query FHIR service with Postman" section, step 2. 

You can also find more synthetic data using Synthea (https://github.com/synthetichealth/synthea). 

Let me know if this is what you're looking for.

**Comment by jagandecapri** [comment]
Hi @evachen96 , thank you for your kind reply. This is what I was looking for. I will close this issue. 🙂
