### ISSUE TITLE
Error in deployment of patientandpopulationservices-smartonfhir-oncg10 on existing Fhir data service.

### ISSUE THREAD

**Issue by Kedar782** [Azure-Samples/azure-health-data-and-ai-samples#247]
I'm trying to deploy the sample patientandpopulationservices-smartonfhir-oncg10 on existing fhir data service.
I can insert the data in the new fhir service using the POSTMAN.
But when I try to add above sample using azd up command on my existing fhir data service I get below error.
I'm following every step mentioned in the deployment document before the azd up command and for azd up command I get below error. (https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/deployment.md)

  (✓) Done: Static Web App: fhirserverproductioncalmed-contextswa (1.668s)
  (✓) Done: App Service plan: fhirserverproductioncalmed-appserv (2.813s)
  (✓) Done: Log Analytics workspace: fhirserverproduc-la (16.567s)
  (✓) Done: Application Insights: fhirserverproduc-appins (18.508s)
  |     ==| Creating/Updating resources (Cache for Redis, Storage account)
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplate: Unable to process template language expressions for resource '/subscriptions/c4cbd8a0-245d-489c-990b-694ac852f414/resourceGroups/fhirdataservice/providers/Microsoft.Resources/deployments/fhirExportRoleAssignment' at line '1' and column '3019'. 'The language expression property 'principalId' doesn't exist, available properties are 'type'.'

TraceID: e9a093a7b272e1db70c1861bf60074de

I selected false in enableVNetSupport option.

Please guide me with this error please.

**Comment by evachen96** [comment]
I see this issue is closed, @Kedar782  do you still need help on this?

**Comment by Kedar782** [comment]
No, I am not.
