### ISSUE TITLE
Error in inferno app on the context app page after selecting the resources (502 Bad Gateway)

### ISSUE THREAD

**Issue by Kedar782** [Azure-Samples/azure-health-data-and-ai-samples#248]
I'm trying to deploy the sample https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/deployment.md.
Here I'm creating a brand new fhir service by not adding anything in existingResourceGroupName parameter while deployment.

I followed every step and when I try to run the first inferno test I get error on the context app stating 502 bad gateway.

I'm not sure what I'm doing wrong in this setup. Please guide me.

![image](https://github.com/user-attachments/assets/9d8cbf19-f368-4c3c-b7ce-0c97bf32942a)

**Comment by Kedar782** [comment]
This is how I invoke the test 1st on inferno.
![image](https://github.com/user-attachments/assets/a1b2c327-0aca-45f2-8c82-fe9dead31705)
![image](https://github.com/user-attachments/assets/4f4eae93-4603-4e80-8c35-7842cfa3bece)

I also tried to enable PKCE with S256 but I get the same result.
I don't know what I'm doing wrong here.

Please guide me.

**Comment by evachen96** [comment]
Thanks for reporting the issue @Kedar782 , the team will take a look and get back to you.

**Comment by Kedar782** [comment]
@evachen96 
I'm getting the gateway url of the API management service from the resource and addding /smart at the end for the fhir server URL in the inferno.

I have followed every step from the documentation.

For this script
powershell ./scripts/Add-FhirUserInfoToUser.ps1 -UserObjectId "<Patient Object Id>" -FhirUserValue "Patient/PatientA"

I have created a new user and added role of FHIR SMART USER in fhir data service only.

Also for object id for this test user, I go to Microsoft Entra ID->All users->Select the test user and get the Object ID from the overview.

I'm following every step in sequence from the documentation.

I don't know what I'm doing wrong here.

I can insert the data using postman clinet credentials (without smart) in my fhir server.

Please let me know if you need any more information from me.

**Comment by Kedar782** [comment]
@evachen96 
These are some settings in inferno client app registrations.

![image](https://github.com/user-attachments/assets/9c05b3b2-5ec0-46de-86ab-3aa9cb2af8b5)
![image](https://github.com/user-attachments/assets/baecfc3f-1720-45cc-986d-f4ef746f51ae)
![image](https://github.com/user-attachments/assets/5221cbae-c776-472e-a92a-c87791254d01)
![image](https://github.com/user-attachments/assets/dabacd92-54cd-43a0-9a5a-b4a07568f504)
![image](https://github.com/user-attachments/assets/418e408d-7cae-4ffe-bf5a-42b74eeba50c)
![image](https://github.com/user-attachments/assets/2fc86128-3f0d-4d7c-bc15-0517be3868e1)


For context application:- 

![image](https://github.com/user-attachments/assets/936da082-d64b-4872-8acd-8d102a83d924)
![image](https://github.com/user-attachments/assets/d4dc0697-37cb-4341-8d31-bcd7781c166c)
![image](https://github.com/user-attachments/assets/553faad1-2d6d-44ae-b55b-1d68bfb1106b)
![image](https://github.com/user-attachments/assets/8e1d8363-06d8-4c06-a4ba-f52e1a81f737)
![image](https://github.com/user-attachments/assets/9de2ef28-36ae-4b8c-a8ef-f36286542c0e)
![image](https://github.com/user-attachments/assets/d9a6ad9a-e61f-4e13-9de1-4aecd8704807)

For Resource Application:- 

![image](https://github.com/user-attachments/assets/3a49081a-430e-4202-aaa2-d5b39afd3437)
![image](https://github.com/user-attachments/assets/7e693cf2-0026-46a6-94ed-a3d979b56554)
![image](https://github.com/user-attachments/assets/894998dd-2154-4598-955a-9d0c19dc7586)


I hope this helps.

**Comment by evachen96** [comment]
Hi @Kedar782  - just FYI that we are still investigating and will let you know as soon as there are any updates. Thanks!

**Comment by Kedar782** [comment]
Ok, thanks for the update.

**Comment by Kedar782** [comment]
Please let me know if you want me to raise a support ticket for this.

**Comment by evachen96** [comment]
Support ticket not needed, as this is a open source sample. Github issues is the channel for open source sample support.

**Comment by Kedar782** [comment]
Do you have any update on this?

Please let me know if you need more information from me.

**Comment by evachen96** [comment]
Hi @Kedar782 , we are working on a fix and will let you know when it's out. Thanks!

**Comment by evachen96** [comment]
Hi @Kedar782 , we have made the fix. Please set up from scratch using the updated code and let us know if there are any more issues.

**Comment by Kedar782** [comment]
Thank you very much Eva for fixing it. It worked.

**Comment by evachen96** [comment]
Great to hear!
