### ISSUE TITLE
Error Getting for the inferno Service Base URL test

### ISSUE THREAD

**Issue by Kedar782** [Azure-Samples/azure-health-data-and-ai-samples#258]
Hello Team,

I have tried to follow every step from this document for the ONC service based url on my fhir server.(FHIR DATA SERVICE).
https://github.com/Azure-Samples/azure-health-data-and-ai-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/ad-apps/inferno-test-app-registration.md#inferno-public-service-base-url

I created a new keyvault with name backkvkeyvault as per the documentation in the same resource where my fhir data service is present.

![image](https://github.com/user-attachments/assets/cd39b594-9f8e-49cd-b708-2598371630fd)

I added all secrets as per the documents inside the keyvault.

They don't have any expiry date.

![image](https://github.com/user-attachments/assets/ee0f7f7f-a5ca-4adc-a185-11a3e73636ee)

![image](https://github.com/user-attachments/assets/7c4677a1-a72e-49cf-b4df-c2f49c8893c3)

But I get error in the inferno for all test cases.

![image](https://github.com/user-attachments/assets/ffd0548f-4c37-49a5-b702-7e6fb54e85ec)

![image](https://github.com/user-attachments/assets/b0f2ca9f-2b41-4f8c-857a-787d39e05341)

In the address I gave apim smart url for my fhir server. I also tried to give fhir data service url without apim but still It is not working.
![image](https://github.com/user-attachments/assets/5ba5cbe5-7252-42ac-8e01-243d5539b8bf)

I will really appreciate your help on this.
Please let me know if you need any information from my side.

**Comment by evachen96** [comment]
Thanks for submitting @Kedar782 . The team will investigate and get back to you!

**Comment by Kedar782** [comment]
I changed the keyvault name to prod-backkv and then I added activation and expiration date for all secrets and still I'm getting same error.

I have other fhir server where I used old code for the service based url testing and it is working on that fhir server. This week I downloaded the latest code for other inferno G10 errors and then I'm getting this issue.

On old fhir server where it is working I see 8 secrets in the keyvault:-

On new fhir server I'm only creating 7 secrets as mentioned in the document:-

**Comment by Kedar782** [comment]
Old Fhir server secrets where it is working:-
![image](https://github.com/user-attachments/assets/4b6f4251-c2d3-40d2-8028-ff84a1b7b997)

New Fhir server where it is throwing error:- 

![image](https://github.com/user-attachments/assets/3489d247-6244-417f-968c-1ed9cf532f67)

**Comment by Kedar782** [comment]
I'm using my fhir service URL without the /metadata in value for address secret:-

https://fhir12calprodsmahealth-fhirdata.fhir.azurehealthcareapis.com

**Comment by Kedar782** [comment]
@evachen96 

Hey Eva,

It worked thanks.

**Comment by evachen96** [comment]
Great to hear @Kedar782 !
