### ISSUE TITLE
Azure AD B2C with g(10) certification Section 7 Multi-patient Requires either ES384 or RS384

### ISSUE THREAD

**Issue by rickgregorypf** [Azure-Samples/azure-health-data-and-ai-samples#259]
It is our understanding that Azure AD B2C does not support the required algorithm for signing tokens and cannot pass the Inferno Testing of Section 7 Multi-Patient Authorization and API. If this solution can be used to pass this section, we are hopeful to hear affirmations to that effect or alternative solutions to address this requirement. Thank you.

**Comment by evachen96** [comment]
Hi @rickgregorypf - Azure AD B2C does not support ES384/RS384, while EntraID does support.
