### ISSUE TITLE
Resource is not getting created with ID I passed in the resource.

### ISSUE THREAD

**Issue by Kedar782** [Azure-Samples/azure-health-data-and-ai-samples#262]
I'm trying to create a new patient with the id 1047. I pass this id in the resource body for the POST API.
Patient resource gets successfully created inside the azure data service but I in the response I get different id for the resource in return.

How can I create a resource with the ID I'm passing?

![image](https://github.com/user-attachments/assets/100babe2-e557-4d39-ae25-5f3ac1489a52)

As you see in the above SS, I passed the ID to the patient as 1047 but in response the patient gets created with the id 177accdf-e53c-44fc-9318-a9dc233ac478.

Please advice. Please let me know if you need any more information from me.

**Comment by evachen96** [comment]
Hi @Kedar782 -
This can be achieved using PUT request. However, there is a risk of unintentionally overwriting existing data if the specified ID already exists. Additionally, the user-provided ID may differ in format from other resource ID's. So, please proceed with caution when doing this. We would recommend doing a GET first to look for the ID before doing the PUT, to prevent accidental overwrites, unless there is a race condition.
