### ISSUE TITLE
Wrong syntax for logical OR

### ISSUE THREAD

**Issue by erikhoward** [Azure-Samples/azure-health-data-and-ai-samples#86]
In the PowerShell script [Create-FhirUserDirectoryExtension.ps1](https://github.com/Azure-Samples/azure-health-data-services-samples/blob/643be63ff7487783c99645b76ddb92fe8455ae1a/samples/patientandpopulationservices-smartonfhir-oncg10/scripts/Create-FhirUserDirectoryExtension.ps1), the syntax is wrong for the logical or on [line 23](https://github.com/Azure-Samples/azure-health-data-services-samples/blob/643be63ff7487783c99645b76ddb92fe8455ae1a/samples/patientandpopulationservices-smartonfhir-oncg10/scripts/Create-FhirUserDirectoryExtension.ps1#L23). 

Should be **+or** instead of '**||**'.

**Comment by sordahl-ga** [comment]
The || logical or is an issue also in these scripts:
Add-FhirUserInfoToUser.ps1
Load-ProfilesData.ps1

**Comment by EXPEkesheth** [comment]
@erikhoward can you please help fix the issue?

**Comment by erikhoward** [comment]
Closing issue.  Fixed in PR #119
