### ISSUE TITLE
Load-ProfilesData.ps1 script fails without generalized consent given to CLI scope

### ISSUE THREAD

**Issue by sordahl-ga** [Azure-Samples/azure-health-data-and-ai-samples#99]
Need to record generalized consent for FhirAudience user_impersonation scope during login to azure cli in Load-ProfilesData.ps1

The line 61 in Load-ProfilesData.ps1 should be changed from:

az login -t $TenantId

to

az login -t $TenantId --scope "$FhirAudience/user_impersonation"

**Comment by EXPEkesheth** [comment]
Thanks @sordahl-ga  for reporting the issue ! We will look into addressing the issue !
